
'use server';

/**
 * @fileOverview A flow for writing original text using AI.
 *
 * - writeText - A function that handles the text writing process.
 * - WriteTextInput - The input type for the function.
 * - WriteTextOutput - The return type for the function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

export const WriteTextInputSchema = z.object({
  prompt: z.string().describe('The prompt to generate text from.'),
});
export type WriteTextInput = z.infer<typeof WriteTextInputSchema>;

export const WriteTextOutputSchema = z.object({
  writtenText: z.string().describe('The original text generated by the AI.'),
});
export type WriteTextOutput = z.infer<typeof WriteTextOutputSchema>;

const prompt = ai.definePrompt({
  name: 'writeTextPrompt',
  input: { schema: WriteTextInputSchema },
  output: { schema: WriteTextOutputSchema },
  prompt: `You are a creative and helpful writer. Based on the following prompt, generate a compelling and original piece of text.

  Prompt:
  \`\`\`
  {{{prompt}}}
  \`\`\`
  `,
});

const writeTextFlow = ai.defineFlow(
  {
    name: 'writeTextFlow',
    inputSchema: WriteTextInputSchema,
    outputSchema: WriteTextOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    return output!;
  }
);

export async function writeText(
  input: WriteTextInput
): Promise<WriteTextOutput> {
  return writeTextFlow(input);
}
