
'use server';

/**
 * @fileOverview A flow for writing text from a prompt using AI.
 *
 * - writeText - A function that handles the text writing process.
 * - WriteTextInput - The input type for the function.
 * - WriteTextOutput - The return type for the function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

const WriteTextInputSchema = z.object({
  prompt: z.string().describe('The prompt to generate text from.'),
});
type WriteTextInput = z.infer<typeof WriteTextInputSchema>;

const WriteTextOutputSchema = z.object({
  writtenText: z.string().describe('The text generated by the AI.'),
});
type WriteTextOutput = z.infer<typeof WriteTextOutputSchema>;

const writeTextFlow = ai.defineFlow(
  {
    name: 'writeTextFlow',
    inputSchema: WriteTextInputSchema,
    outputSchema: WriteTextOutputSchema,
  },
  async ({ prompt }) => {
    const aiPrompt = ai.definePrompt({
      name: 'writeTextPrompt',
      output: { schema: WriteTextOutputSchema },
      prompt: prompt,
    });
    const { output } = await aiPrompt();
    return { writtenText: output!.writtenText };
  }
);

export async function writeText(
  input: WriteTextInput
): Promise<WriteTextOutput> {
  return writeTextFlow(input);
}
